// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"chat/Src/Core/sse"
	application6 "chat/Src/Endpoint/Contacts/Application"
	controller6 "chat/Src/Endpoint/Contacts/Infrestructure/Controller"
	sql6 "chat/Src/Endpoint/Contacts/Infrestructure/Sql"
	application4 "chat/Src/Endpoint/Class/Application"
	controller4 "chat/Src/Endpoint/Class/Infrestructure/Controller"
	sql4 "chat/Src/Endpoint/Class/Infrestructure/Sql"
	application5 "chat/Src/Endpoint/Enrollment/Application"
	controller5 "chat/Src/Endpoint/Enrollment/Infrestructure/Controller"
	sql5 "chat/Src/Endpoint/Enrollment/Infrestructure/Sql"
	application2 "chat/Src/Endpoint/Message/Application"
	"chat/Src/Endpoint/Message/Domain/Repository"
	controller2 "chat/Src/Endpoint/Message/Infrestructure/Controller"
	sql2 "chat/Src/Endpoint/Message/Infrestructure/Sql"
	application3 "chat/Src/Endpoint/Reservations/Application"
	controller3 "chat/Src/Endpoint/Reservations/Infrestructure/Controller"
	sql3 "chat/Src/Endpoint/Reservations/Infrestructure/Sql"
	"chat/Src/Endpoint/User/Application"
	"chat/Src/Endpoint/User/Infrestructure/Controller"
	"chat/Src/Endpoint/User/Infrestructure/Sql"
)

// Injectors from wire.go:
func InitializeContactDependencies() (*ContactDependencies, error) {
    contactSQL, err := sql6.NewMySQL()
    if err != nil {
        return nil, err
    }

    // Use cases
    getAllContactsUseCase := application6.NewGetAllContactsUseCase(contactSQL)
    createContactUseCase := application6.NewCreateContactUseCase(contactSQL)
    deleteContactUseCase := application6.NewDeleteContactUseCase(contactSQL)

    // Controllers
    getAllContactsController := controller6.NewGetAllContactsController(getAllContactsUseCase)
    createContactController := controller6.NewCreateContactController(createContactUseCase)
    deleteContactController := controller6.NewDeleteContactController(deleteContactUseCase)

    contactDependencies := &ContactDependencies{
        GetAllContactsController: getAllContactsController,
        CreateContactController:  createContactController,
        DeleteContactController:  deleteContactController,
    }

    return contactDependencies, nil
}


func InitializeUserDependencies() (*UserDependencies, error) {
	mysql, err := sql.NewMySQL()
	if err != nil {
		return nil, err
	}
	getAllUsersUseCase := application.NewGetAllUsersUseCase(mysql)
	getAllUserController := controller.NewGetAllUserController(getAllUsersUseCase)
	getUserByNameUseCase := application.NewGetUserByNameUseCase(mysql)
	getUserByNameController := controller.NewGetUserByNameController(getUserByNameUseCase)
	createUserUseCase := application.NewCreateUserUseCase(mysql)
	createUserController := controller.NewCreateUserController(createUserUseCase)
	loginUserUseCase := application.NewLoginUserUseCase(mysql)
	controllerLoginUserUseCase := controller.NewLoginUserUseCase(loginUserUseCase)
	userDependencies := &UserDependencies{
		GetAllUserController:    getAllUserController,
		GetUserByNameController: getUserByNameController,
		CreateUserController:    createUserController,
		LoginUserController:     controllerLoginUserUseCase,
	}
	return userDependencies, nil
}

func InitializeMessageDependencies() (*MessageDependencies, error) {
	mysql, err := sql2.NewMySQL()
	if err != nil {
		return nil, err
	}
	getMessageByUserIdUseCase := application2.NewGetMessageByUserIdUseCase(mysql)
	getAllMessageController := controller2.NewGetAllMessageController(getMessageByUserIdUseCase)
	broadcaster := InitializeBroadcaster()
	sendMessageUseCase := ProvideSendMessageUseCase(mysql, broadcaster)
	sendMessageController := controller2.NewSendMessageController(sendMessageUseCase)
	deleteMessageUseCase := application2.NewDeleteMessageUseCase(mysql)
	deleteMessageController := controller2.NewDeleteMessageController(deleteMessageUseCase)
	subscribeMessageController := controller2.NewSubscribeMessageController(broadcaster)
	messageDependencies := &MessageDependencies{
		GetAllMessageByUserController: getAllMessageController,
		SendMessageByUserController:   sendMessageController,
		DeleteMessageByUserController: deleteMessageController,
		SubscribeMessageController:    subscribeMessageController,
	}
	return messageDependencies, nil
}

func InitializeReservationDependencies() (*ReservationDependencies, error) {
	mysql, err := sql3.NewMySQL()
	if err != nil {
		return nil, err
	}
	getAllReservationsUseCase := application3.NewGetAllReservationsUseCase(mysql)
	getAllReservationsController := controller3.NewGetAllReservationsController(getAllReservationsUseCase)
	getReservationByIDUseCase := application3.NewGetReservationByIDUseCase(mysql)
	getReservationByIDController := controller3.NewGetReservationByIDController(getReservationByIDUseCase)
	createReservationUseCase := application3.NewCreateReservationUseCase(mysql)
	createReservationController := controller3.NewCreateReservationController(createReservationUseCase)
	updateReservationUseCase := application3.NewUpdateReservationUseCase(mysql)
	updateReservationController := controller3.NewUpdateReservationController(updateReservationUseCase)
	deleteReservationUseCase := application3.NewDeleteReservationUseCase(mysql)
	deleteReservationController := controller3.NewDeleteReservationController(deleteReservationUseCase)
	reservationDependencies := &ReservationDependencies{
		GetAllReservationsController: getAllReservationsController,
		GetReservationByIDController: getReservationByIDController,
		CreateReservationController:  createReservationController,
		UpdateReservationController:  updateReservationController,
		DeleteReservationController:  deleteReservationController,
	}
	return reservationDependencies, nil
}

func InitializeClassDependencies() (*ClassDependencies, error) {
	classSQL, err := sql4.NewClassSQL()
	if err != nil {
		return nil, err
	}
	getAllClassesUseCase := application4.NewGetAllClassesUseCase(classSQL)
	getAllClassesController := controller4.NewGetAllClassesController(getAllClassesUseCase)
	getClassByIDUseCase := application4.NewGetClassByIDUseCase(classSQL)
	getClassByIDController := controller4.NewGetClassByIDController(getClassByIDUseCase)
	getClassesByTeacherIDUseCase := application4.NewGetClassesByTeacherIDUseCase(classSQL)
	getClassesByTeacherIDController := controller4.NewGetClassesByTeacherIDController(getClassesByTeacherIDUseCase)
	createClassUseCase := application4.NewCreateClassUseCase(classSQL)
	createClassController := controller4.NewCreateClassController(createClassUseCase)
	updateClassUseCase := application4.NewUpdateClassUseCase(classSQL)
	updateClassController := controller4.NewUpdateClassController(updateClassUseCase)
	deleteClassUseCase := application4.NewDeleteClassUseCase(classSQL)
	deleteClassController := controller4.NewDeleteClassController(deleteClassUseCase)
	classDependencies := &ClassDependencies{
		GetAllClassesController:         getAllClassesController,
		GetClassByIDController:          getClassByIDController,
		GetClassesByTeacherIDController: getClassesByTeacherIDController,
		CreateClassController:           createClassController,
		UpdateClassController:           updateClassController,
		DeleteClassController:           deleteClassController,
	}
	return classDependencies, nil
}

func InitializeEnrollmentDependencies() (*EnrollmentDependencies, error) {
	enrollmentSQL, err := sql5.NewEnrollmentSQL()
	if err != nil {
		return nil, err
	}
	getAllEnrollmentsUseCase := application5.NewGetAllEnrollmentsUseCase(enrollmentSQL)
	getAllEnrollmentsController := controller5.NewGetAllEnrollmentsController(getAllEnrollmentsUseCase)
	getEnrollmentsByClassIDUseCase := application5.NewGetEnrollmentsByClassIDUseCase(enrollmentSQL)
	getEnrollmentsByClassIDController := controller5.NewGetEnrollmentsByClassIDController(getEnrollmentsByClassIDUseCase)
	getEnrollmentsByStudentIDUseCase := application5.NewGetEnrollmentsByStudentIDUseCase(enrollmentSQL)
	getEnrollmentsByStudentIDController := controller5.NewGetEnrollmentsByStudentIDController(getEnrollmentsByStudentIDUseCase)
	createEnrollmentUseCase := application5.NewCreateEnrollmentUseCase(enrollmentSQL)
	createEnrollmentController := controller5.NewCreateEnrollmentController(createEnrollmentUseCase)
	cancelEnrollmentUseCase := application5.NewCancelEnrollmentUseCase(enrollmentSQL)
	cancelEnrollmentController := controller5.NewCancelEnrollmentController(cancelEnrollmentUseCase)
	completeEnrollmentUseCase := application5.NewCompleteEnrollmentUseCase(enrollmentSQL)
	completeEnrollmentController := controller5.NewCompleteEnrollmentController(completeEnrollmentUseCase)
	enrollmentDependencies := &EnrollmentDependencies{
		GetAllEnrollmentsController:         getAllEnrollmentsController,
		GetEnrollmentsByClassIDController:   getEnrollmentsByClassIDController,
		GetEnrollmentsByStudentIDController: getEnrollmentsByStudentIDController,
		CreateEnrollmentController:          createEnrollmentController,
		CancelEnrollmentController:          cancelEnrollmentController,
		CompleteEnrollmentController:        completeEnrollmentController,
	}
	return enrollmentDependencies, nil
}

// wire.go:

func InitializeBroadcaster() *sse.Broadcaster {
	return sse.NewBroadcaster()
}

// ProvideSendMessageUseCase creates SendMessageUseCase with broadcaster configured
func ProvideSendMessageUseCase(repository2 repository.IMessage, broadcaster *sse.Broadcaster) *application2.SendMessageUseCase {
	usecase := application2.NewSendMessageUseCase(repository2)
	usecase.SetBroadcaster(broadcaster)
	return usecase
}
